name: vie_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  shadcn_ui: ^0.21.0
  dio: ^5.4.1
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  lucide_icons_flutter: ^1.0.6
  url_launcher: ^6.2.5
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.0.2+1
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
